services:
  app:
    build:
      context: .
      target: final
    env_file:
        - path: .env
          required: false        
    ports:
      - "8080:8080"
    environment:
      DISABLE_EMAILS: "true"
      DATABASE_URL: postgresql://admin:admin@db:5432/eventeasedb
    networks:
      - eventease-net
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eventeasedb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - eventease-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d eventeasedb"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - eventease-net

volumes:
  db-data:

networks:
  eventease-net:
    driver: bridge